
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "graphs_Dennis"
version = "0.1.0"
description = "A Python package for graph algorithms"
authors = [
    {name = "Dennis", email = "rzhao@msudenver.edu"}
]
license = "MIT"
dependencies = []