
[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "graphs_Dennis"
version = "0.1.0"
description = "A package for Dijkstra's algorithm and other graph algorithms"