
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graphs_Dennis"
version = "0.1.0"
description = "A Python package for graph algorithms"
authors = [
    {name = "Denis", email = "rzhao@msudenver.edu"}
]
license = "MIT"
dependencies = []